name: 'CI'

env:
  CI: true
  FORCE_COLOR: true

on:
  pull_request:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'

      - name: Get NPM cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore NPM cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: npm-cache-folder-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-folder-

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'

      - name: 'Install the Node.js dependencies'
        run: npm install

      - name: 'Lint the code'
        run: 'npm run lint'

      - name: 'Add lint summary'
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
  build:
    needs: ['lint']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'
        with:
          submodules: 'recursive'

      - name: Get NPM cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm config get cacheFolder)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore NPM cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: npm-cache-folder-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-cache-folder-

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'

      - name: 'Install the Node.js dependencies'
        run: npm install

      - name: 'Generate the Graph code'
        run: 'npm run codegen'

      - name: 'Build the code'
        run: 'npm run build'

      - name: 'Add build summary'
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
